version: 0.2

env:
  variables:
    NODE_ENV: "production"

phases:
  install:
    commands:
      - 'sudo apt-get update'
      - 'sudo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD'
  post_build:
    commands:
      - 'sudo docker build -t exchange321/accese-api-server:latest -f .docker/Dockerfile .'
      - 'sudo docker push exchange321/accese-api-server:latest'
artifacts:
  files:
    - 'appspec.yml'
    - 'deploy.sh'
